[Detail API] fix for deleting old index value, to update new index value
egraphdb/egraphdb pull request #3
Opened 2019-07-30 07:37 UTC by sujatha-mh

Issue: https://github.com/egraphdb/egraphdb/issues/2

2019-08-02 16:00 UTC, neeraj9 requested changes
please close these before it can be merged with the rest of the codebase.

2019-08-02 16:00 UTC, neeraj9 commented on models/egraph_detail_model.erl
> +                            DbStoredDetailsInfo, RawKey,
Add "RawKey" in separate line.

2019-08-02 16:00 UTC, neeraj9 commented on models/egraph_index_model.erl
> +    {Query, Params} = form_delete_index_base_query(Key, KeyType, IndexName),
You don't have to duplicate so much of code. Instead you could just write a new function to generate query and params instead and reuse most of it there.

```
delete_resource(Key, KeyType, IndexName) ->
    {Query, Params} = form_delete_index_base_query(Key, KeyType, IndexName),
    delete_resource_internal(Query, Params).

delete_resource(Key, KeyType, Value, IndexName) ->
    {Query, Params} = form_delete_index_base_query(Key, KeyType, IndexName),
    Query1 = <<Query/binary, " and id=?">>,
    Params1 = Params ++ [Value],
    delete_resource_internal(Query1, Params1).

delete_resource_internal(Query, Params) ->
    TimeoutMsec = egraph_config_util:mysql_rw_timeout_msec(index),
    PoolName = egraph_config_util:mysql_rw_pool(index),
    case egraph_sql_util:mysql_write_query(
        PoolName, Query, Params, TimeoutMsec) of
        ok ->
            true;
        _ ->
            false
    end.
```

2019-08-02 16:00 UTC, neeraj9 commented on models/egraph_index_model.erl
> +    Query1 = iolist_to_binary([Query] ++ " and id=?"),
Ideally that should be Query1 = <<Query/binary, " and id=?">>,

2019-08-06 05:42 UTC, sujatha-mh commented
I have made the changes as suggested. Please validate and accept this pull request.

2019-08-28 13:50 UTC, neeraj9 commented
Looks good now. Thanks.

2019-08-28 13:50 UTC, merged